### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by ImStarShine** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#101]
-Name/Ign                                                                                                                                        Katrina1023                                                                                                                                                 Reason-
I want to help some new players that dont know the commands in the server and teaching them stuffs    -Do you have expierience of being a staff?
Yes i was a moderator in a server butt i got replaced 
[More information]

-Tell us more about yourself : (please add your age,name)
My real name is Tiffany Wilson Jones (Serioulsly) im 15 yers old play's minecraft often
[situations and other stuff]

--What would be your action if there's a troublemaker?
i will give him/her a warning depending what chaos him/her makes 
-If he/she is a really close friend? Welp i will  still ill give him/her a warning cause im a staff not a protector
-Whats your status? or How long do you stay im online to 8:00 am to 12 pm
-Are you friendly?
yes im friendly but if some one annoys me im angry but still friendly
Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @pinoylifecraftmoderator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by Kaoruuu** [comment]
I created an issue, numbered #100 and read all the new changes in application and if it is closed or not.
