### ISSUE TITLE
Builder Application Poopeater

### ISSUE THREAD

**Issue by Poopeater** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#105]
-Name/Ign:
Poopeater
Reason-
I want to help some newbies that dont know hoy to play and use the command-
-Do you have expierience of being a staff?
no im trying to apply in this server :D
[More information]

-Tell us more about yourself : (please add your age,name birth day)
My real name is johnirvin romay im 16 years old my brithday is sept.3 2000 play's minecraft often
[situations and other stuff]

--What would be your action if there's a troublemaker?
i will give him/her a warning depending what trouble him/her makes
-If he/she is a really close friend?
still ill give him/her a warning cause im a Builder not a protector
-Whats your status? or How long do you stay online?
online to 5:00 am to 8:00 pm
-Are you friendly?
yas im friendly My Freind is MrAinz Harlypasiosane Lesllie  :D

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @pinoylifecraftmoderator
Mentions : @Kaoruuu
Thankyou!!

**Comment by PinoyLifeCraft** [comment]
Unfortunately, as told by the announcement, applications are closed. Sorry for the inconvenience.
