### ISSUE TITLE
Report Ban Meto2 for Griffing

### ISSUE THREAD

**Issue by Poopeater** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#106]
im just leave my items in chest in a short time in pvp arena and he/she wair my 15 stucks of iron ingot
Please ban he/ she please i told he/she to get back my items and dnt give to me :(

**Comment by CornNickel** [comment]
Hindi po namin pwedeng i ban si Meto2, We only ban hackers or related to third party program / mod client (Mc Client) / disrespect the staff (Warning #1 to #3) and advertise other server in chat Thank you ~MrCorn
