### ISSUE TITLE
Troublemakers...

### ISSUE THREAD

**Issue by Kaoruuu** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#13]
Should I really report here because I'm afraid I might do the wrong thing.

**Comment by RagingGod** [comment]
YES:D

**Comment by PinoyLifeCraft** [comment]
Troublemakers? Why?

**Comment by Kaoruuu** [comment]
Well, you see. Even though there are higher ranking officials, I think it's still not enough because they might overlook something else. (Yes.. And that is the part where no one is there to check the server and the troublemakers can do whatever they want). So, there was this time when I am in the server and some players are just advertising stuff and it's repetitive.

**Comment by PinoyLifeCraft** [comment]
So, Block Advertisement ? You meant?

**Comment by Kaoruuu** [comment]
Pardon?

**Comment by Kaoruuu** [comment]
Advertisements weren't prohibited?

**Comment by PinoyLifeCraft** [comment]
Dahil po sa Issue na pag nag sulat ka nito " -.- or facebook.com " it'll not shown :disappointed:

**Comment by Kaoruuu** [comment]
What?

**Comment by PinoyLifeCraft** [comment]
This should be fix in the next Update Thanks for the Report
👍
