### ISSUE TITLE
Rpg

### ISSUE THREAD

**Issue by LiveGhoul** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#14]
A world full of RPG elements and Class :D

**Comment by RagingGod** [comment]
What Do u mean tho?

**Comment by LiveGhoul** [comment]
A server remake or a addition for the upcoming Faction world....

**Comment by PinoyLifeCraft** [comment]
We will try ASAP 👍

**Comment by LiveGhoul** [comment]
Yay :D

**Comment by PinoyLifeCraftModerator** [comment]
There you have it Howard our gms reply

**Comment by LiveGhoul** [comment]
Wait are you MrJue?

 -LiveGhoul-

**Comment by PinoyLifeCraftModerator** [comment]
Yep sorry about that earlier leave of mine i was asked to do chores :)

**Comment by PinoyLifeCraftModerator** [comment]
Household*

**Comment by LiveGhoul** [comment]
I see you misunderstood it ... apologize me for kinda Disrespecting the server thouh xD

**Comment by PinoyLifeCraftModerator** [comment]
What did i misunderstood? XD

**Comment by LiveGhoul** [comment]
yup... 101% xD

**Comment by PinoyLifeCraftModerator** [comment]
I see your a fan of Tokyo Ghoul

**Comment by LiveGhoul** [comment]
kinda ... Tokyo Ghoul is a Master piece for me... A big fan of RPG games here :D
