### ISSUE TITLE
FACTION WARS(As my example for making/applying an Event Manager for the Server;Still needs a Approval from the owner Though)

### ISSUE THREAD

**Issue by LiveGhoul** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#15]
A Faction wars where all Faction Fight.
![images](https://cloud.githubusercontent.com/assets/25541651/22625983/b1b1b9f4-ebdd-11e6-8382-157eb5aa6b82.jpg)
P.S i'll just reply the rules in the comment

**Comment by PinoyLifeCraft** [comment]
Is this an Application or nope?

**Comment by LiveGhoul** [comment]
Sir owner i am wanted to make a Rank or the same as the Staff and other server officers called "Event Manager"
An Event manager guy plans what'll be the next event for the server but still this position need approval from the Owner though..

**Comment by PinoyLifeCraft** [comment]
We're sorry @LiveGhoul but we do not have a " Event Manager " Rank we cannot add more like that...
