### ISSUE TITLE
Staff Application by Howard

### ISSUE THREAD

**Issue by LiveGhoul** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#16]
Name:HowardYangco
IGN:Howard
Age:15
Are you a experienced Staff or Admin?
My answer: Yes , im even an owner of a server/s.
Why do u want to be a Staff?
I wanted to be a Staff because i am professional and a Experienced guy when it comes to this stuffs.
What if your best friend doesn't Follow the Rules and Violate it?
Ill still Ban him/her cause rules are rules we people of the/this server needs to follow it otherwise we'll get banned or kicked for something dull or False things we've done.

So that's all :D Hoping that our beloved Owner accept me :D

**Comment by LiveGhoul** [comment]
@PinoyLifeCraft  I'm applying for Admin or Helper ...

**Comment by LiveGhoul** [comment]
@PinoyLifeCraft 
Dear Staff and Admins on the Server,


    I'm really2x sorry for not onlining for days kasi nag ka dengue ako .. so sana maunawaan niyo na mg lalaro na ako sa Server ulit tnx for unerstanding :D 

                                                        -LiveGhoul-

**Comment by PinoyLifeCraft** [comment]
👍

**Comment by LiveGhoul** [comment]
@PinoyLifeCraft  So kayo lang po decide kung Admin ba ako or Builder Sir ;)
