### ISSUE TITLE
Discord! or a Facebook Group Chat

### ISSUE THREAD

**Issue by LiveGhoul** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#19]
We need to make a Discord in order for us to discuss properly like suggestions and etc.
![discord_logo_svg svg](https://cloud.githubusercontent.com/assets/25541651/22648760/e6ef2206-ec2c-11e6-9660-ffce0d6a275b.png)

https://discordapp.com/
What is Discord?
All-in-one voice and text chat for gamers that’s free, secure, and works on both your desktop and phone. Stop paying for TeamSpeak servers and hassling with Skype. Simplify your life.

**Comment by PinoyLifeCraft** [comment]
https://discordapp.com/channels/278397863778844672
This is our Server Link

**Comment by PinoyLifeCraft** [comment]
To Join in our Server Discord 
[Click me](https://discord.gg/2sduJ)

**Comment by PinoyLifeCraft** [comment]
Pinoy LifeCraft Discord Server is...
[Here](https://discord.gg/QSZ6Sjx)

**Comment by LiveGhoul** [comment]
@PinoyLifeCraft  tnx :D
