### ISSUE TITLE
Enchanted Books Arent Useful :P

### ISSUE THREAD

**Issue by PinoyLifeCraftModerator** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#2]
Reward Ebooks on Crates
Tried+Tested

On anvils
= Not working on gmc too

**Comment by RagingGod** [comment]
Alisin na ung parang ito po (Vote) nameofbook

Walaon na tong vote og parkour

**Comment by PinoyLifeCraft** [comment]
Try po namin...
