### ISSUE TITLE
Staff Application | CornNickel

### ISSUE THREAD

**Issue by CornNickel** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#22]
Name:**Alexsander**
IGN:**CornNickel**
Age:**16**
Are you a experienced Staff or Admin?
My answer: **Yes , I have an experienced being staff/admin of a server in other games , i host a server in cs2d before and other games, it's my responsibilities to help other people in server's like this i love being a part of a server , i want to help other staff** 👍
Why do u want to be a Staff?
**I want to help new player's coming in server, help them in anyway like how to make a money in game, teaching hacker's some lesson, making the server a 100% secured 100% hacker free, i being a host/owner a server before in other games , it's hard being a staff but i want to apply as staff of this server because i want  to help staff of this server and new player's joining in this server. i love being a part of a server/staff I will do my best to make sure this server will be the best server, Thank you in Advance** 👍 

> **Applying for Helper**

**Comment by PinoyLifeCraft** [comment]
We're Sorry but No slot for Moderator :disappointed: 1 for Helper and 3 for Builder nalang po

**Comment by CornNickel** [comment]
Sige sir Helper po ^_^

**Comment by PinoyLifeCraft** [comment]
Well Goodluck :+1:

**Comment by CornNickel** [comment]
Thank you :)

**Comment by PinoyLifeCraft** [comment]
Please PM on our Facebook Page at [Here](https://www.facebook.com/pinoylifecraft/) to 1 on 1 chat with us for a PM Convo...

**Comment by CornNickel** [comment]
@PinoyLifeCraft Okay 👍  ❤️
