### ISSUE TITLE
Staff Application by Richman

### ISSUE THREAD

**Issue by Richman123** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#23]
Can i apply to be a staf my Username is Richman

**Comment by PinoyLifeCraft** [comment]
Please Introduce your self :+1:

**Comment by Richman123** [comment]
Name:Jethro Jay Sayos
IGN:Richman
Age:15
Im live in 313Homelotmainpurok3 Langkaan1DasmarinasCaviteCity.
And Im A grade 9 student in Congressional National HighSchool.
And im playing League of Legends and Minecraft

**Comment by PinoyLifeCraft** [comment]
Wrong Format Please read and Copy
Here ---> #24

**Comment by Richman123** [comment]
IGN:Richman

I want to be a builder

Yes Im staff of new server

Age:15

My name is JethroJaySayos and Im live in 313Homelotmainpurok3 Langkaan1DasmarinasCaviteCity.
And Im A grade 9 student in Congressional National HighSchool.
And im playing League of Legends and Minecraft


[Situations and Other stuff]

I will mute or kick who was making a trouble

If she/he a close friend i will still mute or ban her

Im online in 8Hour's

Yes im a friendly i will help a new player to get earn a money and say the rules of the server

**Comment by Richman123** [comment]
Ilang days po bago  ma approve na maging builder ?

**Comment by reantaso15** [comment]
hello server i want be a builder
