### ISSUE TITLE
staff application by Astonians

### ISSUE THREAD

**Issue by Astonians** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#26]
-Name/Ign: Astonians

-What Rank are you applying for? (1 Helper, 3 Builders) : hmm i want to be helper

-Reason : because i want to help our staffs and moderators and especially to the players of the server 

-Do you have experience on being a staff?* : yes 

[More Information]

-Tell us about Yourself : (please add your age, name) : iam Lance Tobey T Gaño and iam 12 yrs old 

[Situations and Other stuff]

-What would be your action if there's a troublemaker? : i will ask him/her some questions and if he/she did not answer correctly or honestly i will give him/her a punishment (kick) 

-If he/she is a really close friend? : i will still punish him/her because that is my work 

-Whats your status? or How long do you stay online? 4-8 hours per day 

-Are you friendly? : absolutely yes :D

**Comment by MarkPlayz** [comment]
MarkPlayz
Any ranks that i cant help others
I want to help players from bully
Yes
I am Mark Louis C. Capit and i am 13 years old
I wil kick them for a week
I will ask a few question and i will kick them for a while
Im playing minecraft 1-12 hours
Yes im friendly

**Comment by MarkPlayz** [comment]
Kapag naka gawa ako ng mali kick me for a while

**Comment by PinoyLifeCraftModerator** [comment]
@MarkPlayz pls Make a New Issue

**Comment by MarkPlayz** [comment]
MarkPlayz
I want to be a Builder
I want to help the builders and players in server
Yes
I am Mark Louis C. Capit and i am 13 years
Because other staff are trolling players I want to punished them
I will ask a few question and I will put them in jail
Im playing minecraft 5-6 hours
Yes im friendly

**Comment by Kaoruuu** [comment]
@MarkPlayz , Just make your own issue about your application.

**Comment by Astonians** [comment]
sir do i have 10% to be a staff? if i dont have any chance of being helper i can be a builder :D

**Comment by MarkPlayz** [comment]
Kinuha nyo na nga ung mgz idea ko eh....sino ba nakaisip sa jail ako lang
ung nakaisip
