### ISSUE TITLE
CornNickel | Shoutout ^_^

### ISSUE THREAD

**Issue by CornNickel** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#28]
Ito yung shoutout na pinangako ko ^_^ here's the link : https://www.youtube.com/watch?v=VnxjHWBMgyI 

👍  I'll do everything to make this server be the best of the best

**Comment by PinoyLifeCraft** [comment]
Wow... Thank you for your support your Application will Effect soon....

**Comment by PinoyLifeCraftModerator** [comment]
(y)

**Comment by CornNickel** [comment]
> ❤️  You're welcome 😃 Keep it up @PinoyLifeCraft  👍  I really like your server ^_^ Keep what you're doing 👍
