### ISSUE TITLE
staff application by (itsJakeMitchell)

### ISSUE THREAD

**Issue by itsJakeMitchell** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#29]
im itsJakeMitchell

a helper please

cause i want to help poor
players :)

no but i can have now if u hire me.

Im Ian opiso 14 years old and im soo helpful...

yes i will solve the problem by my self :)

im gonna tell her/him that its bad and im gonna ban him he made her/she own decision

im single/8hrs a day or 5hr..

yes i am :)

thank you :+1:

**Comment by CornNickel** [comment]
Copy this #24

**Comment by PinoyLifeCraft** [comment]
Please copy the format from #24

**Comment by itsJakeMitchell** [comment]
huh
