### ISSUE TITLE
add /home command for staff

### ISSUE THREAD

**Issue by PinoyLifeCraftModerator** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#3]

**Comment by PinoyLifeCraft** [comment]
What is it stands for @RagingGod a " PerWorldHome " like go home at SpawnPoint?

**Comment by RagingGod** [comment]
Title is meant as /sethome

Tnk you po salamat

**Comment by Kaoruuu** [comment]
@PinoyLifeCraft
