### ISSUE TITLE
staff aplication by itsJakeMitchell

### ISSUE THREAD

**Issue by itsJakeMitchell** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#30]
-Name/Ign:ByTigerYT

-What Rank are you applying for? (1 Helper, 3 Builders) helper

-Reason :i want to help the poor players and make no cheats

-Do you have experience on being a staff?*no but i can have now

[More Information]

-Tell us about Yourself : (please add your age, name)Im Ian Opiso and Im 14 and soo friendly :+1: 

[Situations and Other stuff]

-What would be your action if there's a troublemaker?i tell him to stop

-If he/she is a really close friend? i dont have choice i will gonna bann him if he/she didnt listen

-Whats your status? or How long do you stay online? 5 hrs a day

-Are you friendly?yes i am

**Comment by Kaoruuu** [comment]
@itsJakeMitchell, 
-What rank are you exactly applying for?

-Even though, fill your Name/IGN.

**Comment by itsJakeMitchell** [comment]
is it my name on minecraft?

**Comment by Kaoruuu** [comment]
@itsJakeMitchell 
I don't want to be frank but IGN means In Game Name, so you have to put your Minecraft User.

**Comment by PinoyLifeCraftModerator** [comment]
yes please fill out your Ingamename (from minecraft)

also pls **Edit Dont Make a new Issue**

**Comment by itsJakeMitchell** [comment]
ok sir :+1:

**Comment by kylecabarle** [comment]
name:akdn
i am applying to be a helper
my reason of applying to be a helper is to help anyone that needs help
im 13 years old my real name is kyle cabarle
if there`s a troublemaker im going to ban them until they learn not to bully anyone
im going to be always online when im a helper because someone needs help
yeah im friendly
