### ISSUE TITLE
By:ClaudiaKAWAII

### ISSUE THREAD

**Issue by ClaudiaKAWAII** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#32]
can i be the adminstator,mod,helper or more please

**Comment by CornNickel** [comment]
Copy the format for application form here @24

**Comment by Kaoruuu** [comment]
Don't make another issue, just edit and use the #24 format.

**Comment by ClaudiaKAWAII** [comment]
Name:ClaudiaKAWAII
i want to apply builders or Admintrator,or Mod
because i want to help people and if someone spamming or breaking something i will report it and i will make my our server beautiful
no because idk first what i do if im staff
my real name in christine and im 10 yeas old im im going to 11 years old in august 19 2006
i will report it in owner if have trouble 
yes i have close firend here he is probuilder03
i stay here in 5 or 6 hours
and im good friendly

**Comment by Kaoruuu** [comment]
Implied 
-What would be your action if there's a troublemaker? (Your answer here is good)

-If he/she is a really close friend? (This one is not on the point, it is asking what would you do if the troublemaker was your close friend?)

**Comment by CornNickel** [comment]
There's no available slot for admin and mod :) only builder.

**Comment by ClaudiaKAWAII** [comment]
ok builder :)

**Comment by Neil09to** [comment]
can i apply to be a Helper

**Comment by PinoyLifeCraft** [comment]
No slots for Helper or Mod ... Builder nalang po 😞

**Comment by Neil09to** [comment]
Builder nalang

**Comment by PinoyLifeCraft** [comment]
Paki update ng Application mo @Neil09to

**Comment by Neil09to** [comment]
where

**Comment by Neil09to** [comment]
san ko makikita ang update

**Comment by PinoyLifeCraft** [comment]
#31

**Comment by Neil09to** [comment]
sulat ko yan

**Comment by Neil09to** [comment]
xD

**Comment by Neil09to** [comment]
wla po ako sa mod

**Comment by Neil09to** [comment]
#31 Staff Application By Neil09

**Comment by Neil09to** [comment]
wala akong makitang  #31

**Comment by ClaudiaKAWAII** [comment]
did my format is good? sir?

**Comment by Neil09to** [comment]
were your format

**Comment by ClaudiaKAWAII** [comment]
and i want builder too

**Comment by Neil09to** [comment]
me too

**Comment by Neil09to** [comment]
san ba na update ang aking application

**Comment by Neil09to** [comment]
#31

**Comment by ClaudiaKAWAII** [comment]
sir are you here???

**Comment by ClaudiaKAWAII** [comment]
@PinoyLifeCraft can i be Builder?

**Comment by PinoyLifeCraftModerator** [comment]
@ClaudiaKAWAII if you want to be a builder we will first observe your skills :)

**Comment by ClaudiaKAWAII** [comment]
ok

**Comment by ClaudiaKAWAII** [comment]
i want to be a builder :smiley:

**Comment by PinoyLifeCraftModerator** [comment]
@ClaudiaKAWAII then if you are free i will observer ir builds in creative :)

**Comment by ClaudiaKAWAII** [comment]
ok

**Comment by ClaudiaKAWAII** [comment]
did im builder now?

**Comment by ClaudiaKAWAII** [comment]
????

**Comment by PinoyLifeCraftModerator** [comment]
We will still observer if you have the skill we need. Also if you are familliar with the world edit plugin
And if your builds passed then we will accept you :)

**Comment by ClaudiaKAWAII** [comment]
oh ok

**Comment by ClaudiaKAWAII** [comment]
how do i know if i accept now or im builders now???

**Comment by ClaudiaKAWAII** [comment]
@PinoyLifeCraftModerator are you still online?

**Comment by PinoyLifeCraftModerator** [comment]
@ClaudiaKAWAII pls w8 for our reply

**Comment by ClaudiaKAWAII** [comment]
ok

**Comment by ClaudiaKAWAII** [comment]
hi guys

**Comment by ClaudiaKAWAII** [comment]
its me ClaudiaKAWAII can i try again to be a builder?
