### ISSUE TITLE
Improvement for Op Survival 

### ISSUE THREAD

**Issue by PinoyLifeCraftModerator** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#33]
**UberEnchants**

https://dev.bukkit.org/projects/uberenchant

Permissions
Defaults to op
uber.add.enchant
uber.clear.enchant
uber.del.enchant
uber.add.lore
uber.clear.lore
uber.del.lore
uber.insert.lore
uber.set.lore
uber.add.name
uber.del.name
uber.set.name

![upload_2016-1-9_19-1-21](https://cloud.githubusercontent.com/assets/24989412/23299887/37d3c5ec-fabe-11e6-9516-7a2e61de2622.png)

===================================================================

**MarriageMaster**

https://dev.bukkit.org/projects/marriage-master?gameCategorySlug=bukkit-plugins&projectID=74734

Permissions:
marry.* - Allows all permissions
marry.admin - Allow to setpriests and reload and also makes you a priest
marry.bypass - Gives all bypassing permissions
marry.user - Gives acces to all user functions
marry.chat.* - Gives acces to all chat options
marry.list - Allow to list all married players
marry.pvpon - Allow to turn pvp with partner on
marry.pvpoff - Allow to turn pvp with partner off
marry.priest - Makes someone a priest
marry.tp - Allow teleport to partner
marry.home - Allow to use the home with the partner
marry.chat - Allow to use the private chat with the partner
marry.chat.color - Allows colors in private messages
marry.chat.format - Allows formating private messages (except magic)
marry.chat.magic - Allows magic format in private messages
marry.kiss - Allows to kiss your partner
marry.gift - Allows you to gift items to your partner
marry.backpack - Allows to share the backpacks (requires Minepacks)
marry.selfmarry - Allows a player to send other players marry requests without the need of a priest
marry.changesurname - Allows to change the surname when self marry is on or if you are a priest.
marry.setpriest - Allow someone to make players to priests
marry.offlinedivorce - Allows a priest to divorce a couple if only one of them is online
marry.listenchat - Allows to see the private chat
marry.skiptpdelay - Allows to skip the tp delay
marry.bypassgiftgamemode - Allows to gift items from creative mode
marry.bypassrangelimit - Allows to bypass the range limit
marry.reload - Allows to reload the config file

===================================================================

**MaxBans**
MOD REALLY NEEDS THIS LIKE RIGHT NOW

https://dev.bukkit.org/projects/maxbans/pages/permissions

All permissions are maxbans.(commandname)

Commands
/unban <name, IP or UUID>
/ban <name, IP or UUID> <reason>
/ipban <name, IP or UUID> <reason>
/tempban <name, IP or UUID> <number> <minutes|hours|days|weeks|etc> <reason>
/tempipban <name, IP or UUID> <number> <minutes|hours|days|weeks|etc> <reason>
/mute <name or UUID>
/tempmute <name or UUID> <number> <minutes|hours|days|weeks|etc>
/kick <name, * for everyone or UUID>
/checkip <name or UUID>
/uuid
/togglechat
/dupeip <name, IP or UUID>
/checkban <name, IP or UUID>
/warn <name or UUID> <reason>
/clearwarnings <name or UUID> <reason>
/unwarn <name or UUID> - Removes a players most recent warning
/unmute <name or UUID>
/history [name] [number of records] - Displays a history of bans, kicks, mutes & more dealt
/mbreload - Reloads the plugin
/mbdebug - Outputs debug information for me if you're having issues!
/mbwhitelist <name or UUID> - Allows the given user to bypass IP bans (Not regular bans! Eg, use for players with siblings who need to be IP banned)
/ipreport - Basically, a mass /dupeip, on everyone who is online
/lockdown [reason]
/forcespawn - Teleports someone to the spawn (Twice, so /back won't work)
/mbreload - Reloads maxbans
/mbimport - Imports vanilla minecraft (And others) bans. 
/mbexport - Export bans to vanilla, MySQL or SQLite databases. (Allows swapping SQLite <-> MySQL), and others ban plugins.
/rangeban <ip1-ip2> [reason] - Bans the IP range from ip1 to ip2 for the supplied reason.
/temprangeban <ip1-ip2> <time> <hours/min/sec> [reason] - Temporary variant of above
/unrangeban <ip> - Removes any RangeBan which overlaps with the given IP. Eg, if 127.0.0.1-127.0.0.5 is banned, unbanning 127.0.0.3 will lift the whole ban on 127.0.0.1-127.0.0.5.

These are the only exceptions:

maxbans.kick.* - kill all
maxbans.notify - allows player to see if banned players tries to join, or when DNSBL discovers a proxy.
maxbans.checkban.self - check your own bans/warns/mutes
maxbans.seebroadcast - see broadcasts, such as kick messages of others
maxbans.seesilent - "bypass" the -s
maxbans.lockdown.bypass - bypass lockdown mode
maxbans.lockdown.use

===================================================================

**Crazy Auction**

https://www.spigotmc.org/resources/crazy-auctions.25219/
https://www.youtube.com/watch?v=AIk-8_8x2hc

***Features:***

Selling Items
Buying Items
Bidding items
Category selector
Easy to use GUI
Customizable messages
Allowing Damaged Items Toggle
Black List Items
Max/Min bidding and buying
And More!!!!

***Commands and Permissions:***

/CA, /AH, /CrazyAuctions
Description: Opens the Auction House
Permission: crazyauctions.access
/CA Help
Description: Shows the Crazy Auctions help menu.
Permission: crazyauctions.access
/CA View <Player>
Description: View a players listed items.
Permission: crazyauctions.view
/CA Sell/Bid <Price> [Amount of Items]
Description: Sell or bid items.
Permissions:
crazyauctions.sell Needed to use the sell command.
crazyauctions.sell.# Replace the # with the max amount they can sell.
crazyauctions.bid Needed to use the bid command.
crazyauctions.bid.# Replace the # with the max amount they can bid items.
/CA Expired/Collect
Description: See you expired or collectable items.
Permission: crazyauctions.access
/CA Listed
Description: See all of your currenly liste
Permission: crazyauctions.access

![0d190f4a03ee1c6309a5cd07c71dcab7d0b63b82](https://cloud.githubusercontent.com/assets/24989412/23329101/b09d475c-fb6b-11e6-9d42-d5877088e478.png)

===================================================================

**Comment by Kaoruuu** [comment]
YEES!

**Comment by PinoyLifeCraftModerator** [comment]
pls dont **EDIT** dahil mag aadd pa ako 👍

**Comment by LiveGhoul** [comment]
Finally natupad narin :D :D :D

**Comment by PinoyLifeCraft** [comment]
Does it works in Minecraft 1.10.2 :question:

**Comment by PinoyLifeCraftModerator** [comment]
UberEnchant tested on my 1.10 spigot server (works)

Crazy Auction seen in vid (works)

MaxBan definitely! (works)

MarriageMaster wews tested (works)
