### ISSUE TITLE
Server is now Open !!!

### ISSUE THREAD

**Issue by CornNickel** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#39]
**Server is now open ^_^  New Ip : 119.81.145.73:51373 

~IMPROVE SERVER CONNECTION !!**

**Comment by PinoyLifeCraft** [comment]
Pinoy LifeCraft IP : play.pinoylifecraft.com will be fix soon 🙂

**Comment by PinoyLifeCraft** [comment]
Already Fix Thanks for the Support :+1: :stuck_out_tongue_closed_eyes:
