### ISSUE TITLE
Recommended Faction Plugins

### ISSUE THREAD

**Issue by PinoyLifeCraftModerator** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#4]
1. Faction
2. EpicRename
3. NoHopperCraft
4. PlayerVaults
5. Trading
6. ChestShop or SignShop (ambot lang)
7. Vault (not player vault)
8. ChestDrop
9. McMMO
10. FloAuction

tag:
link for more info:
(YouTube)

https://www.youtube.com/watch?v=DZdHuLoEG_M&t=2s

(part 2)

https://www.youtube.com/watch?v=DZdHuLoEG_M&t=2s

(part 3)

https://www.youtube.com/watch?v=i6YNxrbFGnU

**Comment by LiveGhoul** [comment]
Vamprism?
