### ISSUE TITLE
Application Builder by reantaso15

### ISSUE THREAD

**Issue by reantaso15** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#41]
Edit your Application ***
 -by Owner

**Comment by reantaso15** [comment]
my name

**Comment by Kaoruuu** [comment]
Your Application doesn't make any sense, please revise it as much as possible to make it understandable.

**Comment by reantaso15** [comment]
pwede maging builder plss

**Comment by Kaoruuu** [comment]
Dear Sir @reantaso15,

I am here (to attempt) to help you but you have still not provided us with the correct information.
Please tell us more about yourself and if you want a guide or you are confused...

You can check this ( #24 ) and that might be good enough to help you.

If you followed as much as what I said for guidance, thank you for your consideration on looking forward to it.

Sincerely,
Kaoru
