### ISSUE TITLE
Staff Application By DigitalPatata (Updated)

### ISSUE THREAD

**Issue by PixelDigits21** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#42]
-Name/Ign:DigitalPatata

-What Rank are you applying for? (3 Builders): I would like to apply as a builder as well please

-Reason :Because I like to build things, although I used to focus more on command blocks I also now focus on building

-Do you have experience on being a staff?: Yes, I had a friend once, I met him on facebook, and he was assigning server staff for his newly made server, and I was assigned as a moderator, I would kick anyone who would not apologize to any players that they have offended theirselves, sadly the server died after two years due to funding issues.

[More Information]

-Tell us about Yourself : (please add your age, name): My real name is Jasper Paolo Carbero Pairez, I am male, I am 14 years old(at the time I wrote this resume), and I love anime, video games and potatoes, for other pieces of my personal information please refer to my facebook account, Jasper Paolo Pairez

[Situations and Other stuff]

-What would be your action if there's a troublemaker?: I would analyze the situation first and warn that troublemaker, if he apologizes for anything wrong that he did to the server or any of the players it's fine, but if he continues to do whatever that he is doing that is causing havoc, I will be forced to kick him or her (If builders have access to kick commands) or report him to one of the online higher ranked server staff.

-If he/she is a really close friend?: I will tell him or her that he/she should stop, if he or she doesn't listen then i will sadly be forced to kick her/him or report her/him.

-Whats your status? or How long do you stay online?:I'm usually online for one or two hours a day due to my parents limiting my use of computers, but sometimes on weekends I have extended computer privileges, I'm also pretty busy on school matters but I still get to follow my usual agenda

-Are you friendly?: I don't know, well honestly I'm neutral, I'm not friendly to people who are not friendly towards me but i'm friendly to people who befriend me back :smile:

-If you are applying for Builder we will first observe your builds in creative: Yes, I will immediately build something on my plot once the server gets reborn :balloon: .

**Comment by Kaoruuu** [comment]
I guess you came in a bad timing, we'll have to see that in the reborn.
