### ISSUE TITLE
Skyblock suggestion By PixelDigits21

### ISSUE THREAD

**Issue by PixelDigits21** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#43]
Hi there! it's me, I would like to suggest a shop that sells redstone, a shop that sells buckets, and a shop that sells ingots of all kinds, There should also be a shop that sells mob eggs and spawners for people who want to do mob farming on their islands :grin:

**Comment by PixelDigits21** [comment]
I'm sorry if I talk like an answer machine XD some people think they're chatting with one if I'm having a convo with them :rofl:

**Comment by sobuza** [comment]
We'll work on that thing . ^_^

**Comment by PixelDigits21** [comment]
hey, i can talk slang too u know, i'm just a bit serious when it comes to things like dis

**Comment by PinoyLifeCraftModerator** [comment]
Please Consider joining our Fb Page so u can post the suggestions.

**Comment by PixelDigits21** [comment]
okie :grin:

**Comment by PinoyLifeCraftModerator** [comment]
I meant Group sorry ^_^

https://m.facebook.com/login/?next=https%3A%2F%2Fm.facebook.com%2Fgroups%2F1902657896673018%3Ftsid%3D0.37109304824844%26source%3Dtypeahead&refsrc=https%3A%2F%2Fm.facebook.com%2Fgroups%2F1902657896673018&_rdr

**Comment by PixelDigits21** [comment]
lol

**Comment by PixelDigits21** [comment]
i dunno why but my Identicon generated some kind of horned knight ._.

**Comment by CornNickel** [comment]
Cute po ako

**Comment by PixelDigits21** [comment]
@CornNickel  yes XD

**Comment by dwaynejames** [comment]
Ok yan ah!
