### ISSUE TITLE
Amil Helper application (Updated)

### ISSUE THREAD

**Issue by AmilJustin** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#46]
[Want to apply for staff? Follow these form and type it Here on This Issue!]

-Name/Ign:
Amil
-Reason :
I want to help newbies in this server like Corn and Kao ru did to me when i just join the server
-Do you have experience on being a staff?*
No I dont this is my first time applying
[More Information]

-Tell us about Yourself : (please add your age, name)
My real name is Justin Amil I'm 14 years old Im playing league of legends when im bored with minecraft
[Situations and Other stuff]

-What would be your action if there's a troublemaker?
I will give him/her a warning depending what trouble he/she makes
-If he/she is a really close friend?
Let's pretend that I have one.I dont really care if she/he is my close friend if she/he is the one who started it I will still warn him/her!
-Whats your status? or How long do you stay online?
I'm single :) Im online 8:00 am to 9:30 pm every day (pwera nalng kung may lakad kami)
-Are you friendly?
Im VERY friendly :)

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by Kaoruuu** [comment]
Dear Sir @AmilJustin,

I am here in an attempt to question you a thing that I do not get in your application.
"-If he/she is a really close friend?", 
*Let's just say we can assume you have one.. What will you do if you have one and the troublemaker was your close friend?

"-What's your status? or How long do you stay online?"
*"I'm always online" isn't a good answer, it's a complete hyperbole. Can you tell me the exact approximation of how long you are online a day? If it's different story with weekends, please specify.

Thank you for your concerns.

Sincerely,
Kaoru

**Comment by Kaoruuu** [comment]
@AmilJustin
Good, now you followed and answered as much as questioned.

Good Luck on your application! Since I do not handle applications, I only help people do the format correctly for them to tell everyone about their own selves and information without any kind of uncertainties. 

You should await for the judgement of the one who manages applications and I believe it's GM himself.

Sincerely,
Kaoru

**Comment by Poopeater** [comment]
Name:Poopeater
Can i apply to be a good Builder?
I want to be a builder beacause ill dont try to be a staff i help another people in this server and ill banned
a abusing players and hackers in 15 years
My Real Name is john irvin romay my age is 16 years old
ill banned all the troublemaker in 3 hours if my close freind i will mute the player in 10 minutes
yes my freinds is many
im staying online everyday
im freindly beacause im so many freind there are so freindly to me i will mute player

**Comment by Chris450** [comment]
@Poopeater Please make your own issue and not in the comments , thank you!

**Comment by dwaynejames** [comment]
Dear Amil Plsss Promote me to Helper
Name:dwaynejames
Reason:I want to help someone
Please Promote me pleasee...

**Comment by dwaynejames** [comment]
[Want to apply for staff? Follow these form and type it Here on This Issue!]

-Name/Ign:
dwaynejames
-Reason :
I want to help newbies in this server like Corn and Kao ru did to me when i just join the server
-Do you have experience on being a staff?*
No I dont this is my first time applying
[More Information]

-Tell us about Yourself : (please add your age, name)
My real name is Dwayne James Morata I am 10yrs old playing dota 2
[Situations and Other stuff]

-What would be your action if there's a troublemaker?
I will give him/her a warning depending what trouble he/she makes
-If he/she is a really close friend?
Let's pretend that I have one.I dont really care if she/he is my close friend if she/he is the one who started it I will still warn him/her!
-Whats your status? or How long do you stay online?
8:00am-10:00am Kung may lakad kami maka online ako ng 5:00pm
-Are you friendly?
Im very friendly i have so many friend in minecraft

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by Poopeater** [comment]
Player din po ako ng Lol gold 4 acc ko
