### ISSUE TITLE
Applying for Staff?

### ISSUE THREAD

**Issue by PinoyLifeCraftAdmin** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#47]
# **Staff Application Form**

- https://plcstaff.typeform.com/to/kMH5qz

**Comment by Kaoruuu** [comment]
Why here? I want to be able to help them, hehe.

**Comment by ImStarShine** [comment]
I Want to Apply Staff As Moderator I Know How To Use //wand and lots of commands and crate key command And I Promise to keep the server clean from hacking and make sure every one is not rude at other players at the server Sign:Katrina1023
