### ISSUE TITLE
Certain FAQ's and Guides about (your) Application.

### ISSUE THREAD

**Issue by Kaoruuu** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#49]
Are you having trouble in your application? I will help you understand how it works.

There are two ways in applying to be a staff in our server.
#24 or Ainz' new way of applying.

How does #24 works?
*It's very easy, you just have to copy the questions and put your very own answers under the question. Now, just make it sensible and easy for people to understand. I will be able to help you make your application better and more understandable and GM will be the one who will judge and manage your application.

How does Ainz' application works?
*It's another way of applying and it's very easy as well, the site gives you specified questions and all you have to do is to answer. Though, I do not have any knowledge of it yet so I won't be able to give you more information about it.

Now, if you still do not get how #24 this is an explanation of every questions listed.
-What is your name or InGameName?
*It asks you what is the name that you usually use in Minecraft because if you're lucky enough, that InGameName might be promoted to staff unless the situation happens to be unfavorable and you're not trusted enough to be one.

-What is the rank you are applying for? (Slots Available Listed Below)
*Just put down what rank do you want to acquire if you are going to be accepted in the staff team?

-Reason/What is your reason for applying?
*Why are you applying on PLC to be a staff? Are you interested or do you love the server? Tell us that much and feel free to say the reason why. 

-Do you have experience on being a staff?
*Do not lie about this, this is a critical question that will affect your image and your application. Tell us your experiences on being a staff, have you once became a staff in a server? Not just a server, let's say a group community. Have you experienced being an admin or group moderator? Again, tell us in your application.

[More Information]
*This is very important too, even though they are kind of useless. They are very important to create an image and create our opinions about you.

-What would be your action if there's a troublemaker?
*This one is an important question for being an extra question. In case that you don't have an experience being a staff, this could help us identify you and it just basically means "What would you do if a troublemaker creates trouble in the server and imagine yourself as a staff helping in the management of the server?"

-If he/she is a really close friend?
*What would be your action if the troublemaker was a close friend? Would your action change? Would you favor him and not punish him/her? The judgement depends on the answer.

-What's your status? or How long do you stay online?
*This doesn't ask if you're single or not. It asks how long you mostly go online or are you going to be busy these days? Tell us more as much as possible. If you don't have an accurate answer, please give at least an approximation.

-If you are applying for Builder we will first observe your builds in creative.
*This one is important, don't just rely on your application because if you applied and we haven't seen you go to the server then you failed to exceed or fulfill our expectations and it just means you don't have passion in being a staff or pretty much giving us an idea that you don't care. GM will be the one to decide or an Admin? Maybe? Its purpose is for GM to accept your application if he thinks you're a good builder and you're good enough for it.

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu
*These mentions mechanism are important, it notifies us that someone has created an application and someone wants to be a staff. Also, about the "Note : Still "Lacking of Information?", kindly ask. Its purpose is for us to be able to ask or question you freely in case there's an uncertainty somewhere in your reasons. In short, its purpose is to clear up things that people do not understand. So, make good use to it.

Certain Responsibilities and Slots left for the Staff Team Ranks
- GM
They are the "Master" of the community. Meaning to say, they are the owners. Not hiring people for this rank and no slots left for this rank.
Commands Available for GM : 
I think they can do everything in the server.

- 2/5 Admins
People that have great responsibilities and good at managing the Server or at least this community. This rank needs very trusted people. There are 3 slots left for Admin Rank
Commands Available for Admin : 
Almost every Commands and I don't know the limitations due to /op

- 2/5 Moderators
People which specializes in moderating and should be trusted. Mostly, we recommend Moderators that have an experience in handling a community because they are most likely the one who could fit for the rank. There are 3 slots left for Moderator Rank.
Commands Available for Moderator : 
Ban (Temp/IP)
Kick Command
Mute Command
World Edit Commands
Disguise
CE
Give Command
Pay
Gamemode (Creative, Survival, Adventure, Spectator)
Kill Command
TP/TPO
Sudo
EnderChest
Additional PV slots
Heal
Feed
Invsee
Jail
Whois
Speed
Vanish
Warp
Weather
Time

- 5/5 Helpers (2 new recent helpers accepted in the staff team)
People which specializes in helping people, guiding people and trusted are to be hired. There are no slots, meaning it's full.
Commands Available for Helper :
Kick Command
Mute Command
World Edit Commands
Disguise
Gamemode (Creative, Survival, Adventure)
Give Command
Pay
Enderchest
Additional PV slots
Heal
Feed
Speed
Vanish
Warp
Weather
Time

- 1/5 Builder(s)
People who are good at building, who have passion and trusted are to be hired. There are 4 slots left for Builder Rank.
Commands Available for Builder : 
Mute Command
World Edit Commands
Disguise
Gamemode (Creative, Survival, Adventure, Spectator)
Give Command
Enderchest
Additional PV slots
Heal
Feed
Speed
Vanish
Warp
Weather
Time

Ranks and their list of respective players : (These names are InGameName)
GM : JeddGwapz, MinecraftJohn
Administrators : Kairo, Ainz
Moderators : Kaoru_24, Chris
Helpers : sobuza, xxxyyzzc, CornNickel, Amil, ByBlue
Builder(s) : Elu_crack

B-But, you don't have permission for this.
*This is not a need-for-permission issue post, this is just an informative issue regarding applications. So, no harm was made into making this issue.

Make this issue as a reference as much as possible if you see someone wanting to apply but is troubled in mind. This might be a great help.

Before this ends, I'll say something and it is about the application rules. (Very few and simple ones)
-Do not create another issue when told to revise your application.
-As much as possible, it should be grammatically correct so it's much more understandable.
-Also, no one is forcing you to speak in English. So, make an application in Tagalog Language if you want. 
-Again, as much as possible, give us information as much as you can. It helps us understand you.
-Do not lie in your application, it reflects your image.
-Do not put/post your own staff application on someone's application issue, create your own application issue.

This issue is probably non-ending as ideas will come all over again. So, this issue is ongoing and still might be updated.

This is all regarding what I wanted to say to you all as a guide?
Mentions: @PinoyLifeCraft
(Translations in Filipino will be put into another issue afterwards)
-Last Edited : Approximately 12:28 AM and then later 12:56 AM of 5/1/2017

**Comment by CornNickel** [comment]
🥇

**Comment by PinoyLifeCraftModerator** [comment]
NOICE - ( ͡° ͜ʖ ͡° )

**Comment by PixelDigits21** [comment]
Corn srsly? XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD UR PROFILE PIC, DA AMAZING URBAN LEGEND LUCIA JOAQUIN

**Comment by Chris450** [comment]
Lucia is on fleek <3

**Comment by Chris450** [comment]
"GM will be the one to decide or an Admin? Maybe? Its purpose is for GM to accept your application if he thinks you're good to be (specify) and is derving to be (specify)

-@Kaoruuu I think we (staffs) should make a poll on this

**Comment by Kaoruuu** [comment]
@Chris450, I didn't entirely said that "GM will be the ONLY one who will decide" I just said "GM will be the one to decide or an Admin". So, I guess he can still ask for our opinions as much as possible. 

I think even staff members can recommend people to make their chance go higher in being accepted.
