### ISSUE TITLE
Staff Abuse By:Katrina1023

### ISSUE THREAD

**Issue by ImStarShine** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#53]
im reporting Admin:Ainz For killing me and he didnt gave back my items only because im in his faction home and ImHaxingL wants to tp and Admin:Ainz Kill Me

**Comment by PinoyLifeCraftAdmin** [comment]
NOICE

**Comment by Chris450** [comment]
lol. @ImStarShine we are not resposible for any loss you have.. a play is a play..

**Comment by Kaoruuu** [comment]
Sorry but this is not classified as a staff abuse, any more false reports might lead you into taken care by us because these kind of reports are kind of multiplying in an annoying method.

**Comment by AmilJustin** [comment]
LOL ni report talaga
