### ISSUE TITLE
Helper Application By:Katrina1023

### ISSUE THREAD

**Issue by ImStarShine** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#57]
I Want To Apply Staff As Helper To Help Every One In The Server But Not Giving Them What They Want Like Diamonds And Stuff :D :D tnx

**Comment by Kaoruuu** [comment]
Seriously? Wrong format and you created two issues just for your application. Do not make anyone notice you by that annoying method.

Please follow our #24 method.

**Comment by ApachePvP** [comment]
I Want to Apply as Helper to Help Other Staffs and Help the server.
