### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by Soulbeast** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#6]
Hello, I would like to apply as a staff member in this server.. I was once a staff member in UprisingMC but we had some fund problems there and so we had to take it down. I would like to apply as a Builder in the server or a Developer. I have experiences with building skills and I also have a bit of experience in developing. I hope I get a chance to get a spot in the staff.. thank you :)

               
-SoulBeast

**Comment by PinoyLifeCraft** [comment]
Hello SoulBeast your Application Labeled but we need more time to Observe you and so on to Approve you in your Application... And Give us your Facebook Name...

**Comment by PinoyLifeCraft** [comment]
Hello SoulBeast your Application is now Labeled **Application** but we need more time to Observe you and so on to Approve you in your Application... And Give us your _Facebook Name_...

**Comment by Soulbeast** [comment]
I'm sorry but I can't expose my facebook to anyone or for the people I
haven't met before, but I am willing to give my twitter name so we could
chat there maybe?..

**Comment by Soulbeast** [comment]
Tell me your name in Facebook and I will try to find and add you..

**Comment by PinoyLifeCraft** [comment]
No Just Message us on our [Facebook Page](https://www.facebook.com/pinoylifecraft/) ...

**Comment by RagingGod** [comment]
ahhaahha

**Comment by RagingGod** [comment]
can i leave a question here ? :) hehe 

this is for our servers safety
are you really an UprisingMc Staff?
if you are we need proof:

hehehe :) 👍

**Comment by RagingGod** [comment]
if better may screenshot po ba kayo kasama ang ibang staff ng upmc?

**Comment by PinoyLifeCraft** [comment]
Please don't forget to make a cartoon pic 
Here is the link and give it to MinecraftJohn the pic https://www.cartoonify.de/
