### ISSUE TITLE
Raiding Of ImHaxingL

### ISSUE THREAD

**Issue by ImStarShine** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#60]
Pls ban imhaxingl because he raid byblue's base also my fac home can you pls ban him fo
![2017-04-30_17 20 27](https://cloud.githubusercontent.com/assets/25697679/25563226/2dfa43f0-2d4c-11e7-9d4e-bca2f00b3ac5.png)
r this
![2017-04-30_17 20 17](https://cloud.githubusercontent.com/assets/25697679/25563233/5bd38d4a-2d4c-11e7-9ee0-5b70ad90e897.png)
pls ban imhaxingl for raiding byblues base made by:admin Ainz

**Comment by Kaoruuu** [comment]
No, do you not get it? Raiding is normal in Faction. So, your player report is invalid.
Please, stop this at once or we'll really take care of you.
