### ISSUE TITLE
Magical helper application 

### ISSUE THREAD

**Issue by Magicals** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#64]
-Name/Ign:
Magical
Reason-
I want to help some newbies newbs that dont know the commands here 
-Do you have expierience of being a staff?
Yes i was a builder in a server
[More information]

-Tell us more about yourself : (please add your age,name)
My real name is prince louie (Serioulsly) im 13 yers old play's minecraft often
[situations and other stuff]

--What would be your action if there's a troublemaker?
i will give him/her a warning depending what trouble him/her makes
-If he/she is a really close friend?
Hmmmm still ill give him/her a warning cause im a helper not a protector
-Whats your status? or How long do you stay online?
im single :D im online to 8:00 am to 8 to 9 pm
-Are you friendly?
yas im friendly but when it comes to raiding im angry :D but still im friedndly

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by dwaynejames** [comment]
Hi Magical!!!

**Comment by dwaynejames** [comment]
Prince Louie diay huhhhh

**Comment by dwaynejames** [comment]
Hindi ka mapropromote magical!!! sabi ni kaoru kapag long days na hinde ma cocoment na e-propromote ka edi hindi ka mapropromote gaya ko:DDDxD
