### ISSUE TITLE
ApachePvP Helper Application

### ISSUE THREAD

**Issue by ApachePvP** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#65]
-Name/Ign-
ApachePvP
Reason-
i want to help the server and the other staffs and players
-Do you have expierience of being a staff?
Yes Being Admin in other server

[More information]
-Tell us more about yourself : (please add your age,name)
My name is Keith Lourence W. Mabao and my age is 13 years old
--What would be your action if there's a troublemaker?
I will give him/her a warning if he don't stop i will ban him or mute
-If he/she is a really close friend?
Ahhh if he troublemake i will give him warning and if he don't stop i will ban him
-Whats your status? or How long do you stay online?
I am a student 12+ hours
-Are you friendly?
Yes I am if there was need help i help them

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by Kaoruuu** [comment]
@ApachePvP
Sorry but Helper rank is full at the moment, Builder rank is not full though so you can apply for it.

If you're willing to be a Builder, edit your issue.
