### ISSUE TITLE
imHaxingL application for helper

### ISSUE THREAD

**Issue by imHaxingL** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#71]
IGN : imHaxingL

IRL Name : John

Reason : I want to be a helper because I want to help players. I noticed that other staff members don't even answer my questions. I wonder how they treat other players.

No experience of being a staff member.

Real name is John I'm 13 I love playing Minecraft. And I like doing my thing at night when everybody is asleep.

If there was a troublemaker I'll /warn them.And if they do it again for example they were trashtalkin I'll /mute them.

I'm single. I play at least 12pm - 9 pm

I'm very friendly. :)

Really hope I get accepted. :)

**Comment by Kaoruuu** [comment]
@imHaxingL 
Helper is full, we are only accepting builder applications.
