### ISSUE TITLE
i did nothing

### ISSUE THREAD

**Issue by ApachePvP** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#74]
Whyyyyyyyyyyyyyyyyyyyyyy

**Comment by PinoyLifeCraftAdmin** [comment]
Ok ok **If You are certain You did nothing can you explain this please** If the staffs approve of your explanation then i will unban you ^_^...


![2017-05-02_12 19 20](https://cloud.githubusercontent.com/assets/24989412/25614685/9719336c-2f65-11e7-80b5-645798d8dbcd.png)
![2017-05-02_12 20 32](https://cloud.githubusercontent.com/assets/24989412/25614684/9718352a-2f65-11e7-8c9b-f316fb7fac51.png)
![2017-05-02_12 20 35](https://cloud.githubusercontent.com/assets/24989412/25614683/9716f584-2f65-11e7-8b8f-d79c0dd10dae.png)
![2017-05-02_12 20 37](https://cloud.githubusercontent.com/assets/24989412/25614686/9720dcfc-2f65-11e7-99cc-d3f35bfa80d0.png)
![2017-05-02_12 20 50](https://cloud.githubusercontent.com/assets/24989412/25614687/973d80c8-2f65-11e7-8dba-2ab51c61480c.png)
![2017-05-02_12 24 26](https://cloud.githubusercontent.com/assets/24989412/25614688/97484260-2f65-11e7-8a50-0e4f95b379cd.png)
![2017-05-02_12 04 16](https://cloud.githubusercontent.com/assets/24989412/25614689/974f5474-2f65-11e7-9a88-5bfbb8812efa.png)
![2017-05-02_12 06 30](https://cloud.githubusercontent.com/assets/24989412/25614690/974fff32-2f65-11e7-844f-45346583645f.png)
![2017-05-02_12 06 34](https://cloud.githubusercontent.com/assets/24989412/25614691/9769347a-2f65-11e7-9fc7-c74ea02ece25.png)
![2017-05-02_12 06 37](https://cloud.githubusercontent.com/assets/24989412/25614692/9775c3d4-2f65-11e7-864c-66fcbc5ed27b.png)
![2017-05-02_12 06 38](https://cloud.githubusercontent.com/assets/24989412/25614693/97809bec-2f65-11e7-8e9a-655143bda592.png)
![2017-05-02_12 06 40](https://cloud.githubusercontent.com/assets/24989412/25614694/978293d4-2f65-11e7-9909-f079a7bead26.png)
![2017-05-02_12 08 56](https://cloud.githubusercontent.com/assets/24989412/25614695/97926228-2f65-11e7-9c53-461985dd4931.png)
![2017-05-02_12 18 29](https://cloud.githubusercontent.com/assets/24989412/25614696/979ba2de-2f65-11e7-8deb-9b3a59dc1d76.png)
![2017-05-02_12 18 43](https://cloud.githubusercontent.com/assets/24989412/25614697/97a2b812-2f65-11e7-8808-df66d8d4e1ee.png)

**Also im a bit surprised if you did nothing wrong, then why did you quit, when i pmed you.....**

**Comment by PinoyLifeCraftAdmin** [comment]
**I pmed you..... Hey _then quits**_

**Comment by Magicals** [comment]
HAI SINO MERON LAPIZ XD?

**Comment by dwaynejames** [comment]
LOOLLLL X-ray Vision KIck Him!!
