### ISSUE TITLE
Application dwaynejames Helper

### ISSUE THREAD

**Issue by dwaynejames** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#78]

**Comment by dwaynejames** [comment]
Please @PinoyLifeCraft Kao ru Promote me to helper

**Comment by PinoyLifeCraftAdmin** [comment]
in making an application form pls do not copy application forms of other peoples or i will be automatic **Decline!**

**Comment by dwaynejames** [comment]
What is my exam @PinoyLifeCraft ??
