### ISSUE TITLE
Builder Application DutertePresident

### ISSUE THREAD

**Issue by DutertePresident** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#82]
-Name/Ign:
DutertePresident
Reason-
I will tell the admin that what is the bug and other problems in your server
-Do you have expierience of being a staff?
Nope im in first time
[More information]

-Tell us more about yourself : (please add your age,name)
MMy real name is ChrisLawrence im in 8yrs old and i always play minecraft sometimes G.T.A:DD
[situations and other stuff]

--What would be your action if there's a troublemaker?
Warn him/her
-If he/she is a really close friend?
I will warn him/her if he.she trouble your server..
-Whats your status? or How long do you stay online?
Im single:DDDD I always playing minecraft exept at very night and day
-Are you friendly?
Yes im very friendly!!!:DDDD

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

**Comment by PinoyLifeCraftAdmin** [comment]
Are you friendly? No ive seen you in the server too much...

**Comment by dwaynejames** [comment]
Promote me @PinoyLifeCraftAdmin plss

**Comment by dwaynejames** [comment]
Master na kaayo mag English bayyy

**Comment by PinoyLifeCraftAdmin** [comment]
Please do not ask for promotion, this just leads to auto decline on your application.

Pls do not Make issue's about bans with no reason.

Pls do not Make issue's with small descriptions, This is A Forums Not A chatbox.

If you have anything to say Post it on our Fb Page or Join the Group.

**Comment by dwaynejames** [comment]
Ok sorry for all
