### ISSUE TITLE
Please Ban dutertepresident

### ISSUE THREAD

**Issue by dwaynejames** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#83]

**Comment by dwaynejames** [comment]
Jai

**Comment by dwaynejames** [comment]
Wah nalang sya I ban

**Comment by Kaoruuu** [comment]
Okay, you request to ban him but what is your reason for it?

**Comment by Kaoruuu** [comment]
I have to warn you for this, another ban request without sufficient proof is not tolerable. So, I suggest you don't do that again.

**Comment by dwaynejames** [comment]
Sorry @Kaoruuu because I disturb your PLC website:(
