### ISSUE TITLE
Zeref Staff Application Builders

### ISSUE THREAD

**Issue by ZerefDragnel** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#84]
-Name/Ign:Zeref

-What Rank are you applying for? (3 Builders): I would like to apply as a builder as well please

-Reason :Because I like to build things, although I also now focus on building 

-Do you have experience on being a staff?: No, but i will do my best. 

[More Information]

-Tell us about Yourself : (please add your age, name): My real name is Jniño Javeluna i`m 15 years old.I live in Lapyahan labogon mandaue city cebu.My father`s name is Joselito R. Javeluna My mother`s name is Leoncia L. Javeluna.

[Situations and Other stuff]

-What would be your action if there's a troublemaker?: I would analyze the situation first and warn that troublemaker, if he apologizes for anything wrong that he did to the server or any of the players it's fine, but if he continues to do whatever that he is doing that is causing havoc, I will be forced to kick him or her (If builders have access to kick commands) or report him to one of the online higher ranked server staff.

-If he/she is a really close friend?: I will tell him or her that he/she should stop, if he or she doesn't listen then i will sadly be forced to kick her/him or report her/him.

-Whats your status? or How long do you stay online?:I'm usually online for 12 or 11 hours a day 

-Are you friendly?: I don't know, well honestly I'm neutral, I'm not friendly to people who are not friendly towards me but i'm friendly to people who befriend me back 😄

**Comment by Kaoruuu** [comment]
I know you made a mistake in your first issue and created another issue but please do not do that again. Do not create another issue if told to revise your application because it adds the numbers of issues in the repository in an annoying method and then some contents are just similar..

**Comment by ZerefDragnel** [comment]
sorry

**Comment by ZerefDragnel** [comment]
Sorry
