### ISSUE TITLE
Application Builder dwaynejames

### ISSUE THREAD

**Issue by dwaynejames** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#85]
-Name/Ign:dwaynejames

-What Rank are you applying for? (3 Builders): I want to be a Builder because this is my first time i want...

-Reason :Because i will said the bugs and I like To Build Something nice:D

-Do you have experience on being a staff?: No because this is my first time but i will do my best i have:DDD

[More Information]

-Tell us about Yourself : (please add your age, name): My real name is Dwayne James 10yrs old i have brother named ChrisLawrence8yrs old(That DutertePresident in Minecraft)and my mother named leila morata and my father named jay anthony morata thats all:DD

[Situations and Other stuff]

-What would be your action if there's a troublemaker?:I will warn him/her from the help of Builder's permissions and essentials.I will say him/her that dont make trouble in PLC server if he/she tried to trouble the PLC server i will warn him/her or banned(If Builder have perm Ban) if he/she make so much trouble

-If he/she is a really close friend?:I will warn him/her because im not him/her protector in PLC server and let him live in nice place so that he cant ask me for gold and etc.
-Whats your status? or How long do you stay online?Im Single,IM only in 9:00am - 10:00am and in afternoon i will online in 2:00pm-3:00pm:DD

-Are you friendly?: I will honestly that im not so friendly im angry sometimes but im a friendly small:D

**Comment by Kaoruuu** [comment]
I know you want to apply for staff but please do not create spam issues in the repository, it's getting repetitive.

**Comment by dwaynejames** [comment]
Sorry for that spam deh na yun mauulit promise

**Comment by dwaynejames** [comment]
I'm waiting for an comment if I will promoted thank you....Kaylang po ba and promotion??Nag tatanong lang po.

**Comment by PinoyLifeCraft** [comment]
Hello there @dwaynejames,

We have observe you last days and it seems you are not the player we wishing to be a builder 🙁 We're so sorry about that bad review @dwaynejames 

Best Regards,
GM : MinecraftJohn
Pinoy LifeCraft GameMaster
