### ISSUE TITLE
Application For Builder harlypasiosane

### ISSUE THREAD

**Issue by HARLYPash0313** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#88]
Name:harlypasiosane
Can i apply to be a good Builder?
I want to be a Builder Because I want to help our server improve and i will banned
a abusing players and hackers in 2 to 3 years
My Real Name is Harly Dean A. Pasiosane my age is 15 years old
Ill banned all the troublemaker in 6 hours if my close friend i will mute the player in 15 minutes
Yes my friends is Poopeater,Getrex,Amil,Kauro and Ainz
Im staying online everyday except Sunday because Im always in church.
I hope to accept my application.
THANK YOU..

**Comment by Kaoruuu** [comment]
Sorry but "I'm staying online everyday" is not a good phrase for the question.

Can you please tell us at least an approximation on how long you stay online everyday?

I just need to know.

**Comment by dwaynejames** [comment]
wew deh parin maging staff.

**Comment by PinoyLifeCraft** [comment]
Hello there @dwaynejames ,

We are really finding the right person/player to handle a position as a builder. We need to observe you clearly. Hope you understand.

Best Regards,
GM : MinecraftJohn
Pinoy LifeCraft GameMaster
