### ISSUE TITLE
Aplication "Owsla"

### ISSUE THREAD

**Issue by Owsla123** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#90]
In-game name? (Not your Nickname): Owsla
Age? (You must be 13 to apply.): 13
Any previous server bans? (Why, please use detail.):No
Can you Record? (Yes or No.): Yes
-You can download a free recording software.
Why have you decided to apply? (In Detail): because i want to help the server :)
How long have you played on pinoylifecraft ? (Doesn't have to be exact): 3weeks
Timezone? (Exact): Philippines Time Zone - Philippines Current Time - Daylight Saving Time
Do you have Teamspeak and Skype? (Please don't post your skype here 'Yes or no'): Yes
Do you have any experience with server Moderation? (Explain in Detail): I have been mod on other servers. i have been a mod and was gonna do staff series on it but i hade some problems.
Had any name changes? (List Them): yes. Lolo_FY
Anything else you would like to tell us?: I like to say that i really want to help the server ;D <3

**Comment by Owsla123** [comment]
ill be patiently waiting for any reply or reaction ..thank you

**Comment by Magicals** [comment]
:D? MAGICAL HERE

**Comment by Magicals** [comment]
o.0 ur a mod on a diffrent survur i was a op in a another surveur

**Comment by Kaoruuu** [comment]
Okay, I like how you put different informations about you but sadly, that format is wrong.

Please follow our #24 format.

**Comment by dwaynejames** [comment]
wew hindi parin maging staff

**Comment by DutertePresident** [comment]
Di ka mag stataff kasi bobo ka 
-DutertePresident

**Comment by PinoyLifeCraftAdmin** [comment]
@DutertePresident  pls do not reply the only. Pls do not trashtalk persons application forms cause i know your attitude.

**Comment by PinoyLifeCraftAdmin** [comment]
@Owsla123 Sorry but we arent going to accept you, for what you did last night.

Staff's Need some respect, and now you are a staff on another server, you need respect too.
