### ISSUE TITLE
Please ban dutertepresident

### ISSUE THREAD

**Issue by dwaynejames** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#93]
Reason:Sabi nya balikan items pero hindi nya binalik lahat items at si king bagohan pa pinatay nya at hindi nya rin binalik Not Honest DutertePresident

**Comment by dwaynejames** [comment]
Wag nangalang nagpatawad na sya saakin

**Comment by dwaynejames** [comment]
Ban po syaaa

**Comment by dwaynejames** [comment]
Ban plsss

**Comment by PinoyLifeCraftAdmin** [comment]
@dwaynejames  pls do not ask for bans, without reason.. This is a **Forums** not a Chat Box!

**Comment by PinoyLifeCraft** [comment]
Hello there @dwaynejames ,

We need your evidence like Pictures,vid,screenshots,etc.

Best Regards,
GM : MinecraftJohn
Pinoy LifeCraft GameMaster

**Comment by dwaynejames** [comment]
Ganyan po bah @PinoyLifeCraft
