### ISSUE TITLE
MCBean Application Builder

### ISSUE THREAD

**Issue by MinecraftBean** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#94]
-Name/Ign:MCBean

-What Rank are you applying for? (3 Builders): I want to be a builder because this is what i  want:DDD Im also focusing in Build:DD

-Reason : I will say the all bugs to make the server nice and to build something project:D

-Do you have experience on being a staff?: No, But i will do my best because this is i want

[More Information]

-Tell us about Yourself : (please add your age, name): IM 13yrs old my real name is James im playing dota 2 if im bored in minecraft but 5hours i will bored in minecraft

[Situations and Other stuff]

-What would be your action if there's a troublemaker?:I will warn him from the perm. of the builder and essentials i will warn him and said dont do that again because you destruct the server.
-If he/she is a really close friend?:I will warn him/her because im not the protector of him/her and that he/she can realize that playing minecraft wisely is nice:DD
-Whts your status? or How long do you stay online?IM single:DD Im only 5hours a day

-Are you friendly?: Im friendly but i angry if they raid my base

Thank you Newbie pa po ako

**Comment by dwaynejames** [comment]
That's ok

**Comment by PinoyLifeCraftAdmin** [comment]
@dwaynejames pls do not reply to other persons application form. Doing This again will result to you being banned....

**Comment by PinoyLifeCraftAdmin** [comment]
@MinecraftBean Tnx Pls get on touch with us and w8 for some replies 👍

**Comment by dwaynejames** [comment]
Sorry

**Comment by DutertePresident** [comment]
im mcbean
