### ISSUE TITLE
Magicals builder application

### ISSUE THREAD

**Issue by Magicals** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#96]
[Want to apply for staff? Follow these form and type it Here on This Issue!]

-Name/Ign:Magical

-What Rank are you applying for? (3 Builders)

-Reason : because i like building stuff

-Do you have experience on being a staff?*yep im a op in miexcraft beta and the release too

[More Information]

-Tell us about Yourself : (please add your age, name)
My name is prince :D seriously and my age is 13
[Situations and Other stuff]

-What would be your action if there's a troublemaker?
He/she will be warned
-If he/she is a really close friend?
still he/she will be warned
-Whats your status? or How long do you stay online?
8:00am to 9:00 pm and im single
-Are you friendly?
YUS VERY FRIENDLY
-If you are applying for Builder we will first observe your builds in creative

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here![Want to apply for staff? Follow these form and type it Here on This Issue!]

**Comment by dwaynejames** [comment]
Friendly to badly
