### ISSUE TITLE
Helper Application By Poopeater

### ISSUE THREAD

**Issue by Poopeater** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#99]
Name:Poopeater
Can i apply to be a good Helper?
I want to be a Builder Because I want to help our server improve and i will banned
a abusing players and hackers in 3 to 5 years
My Real Name is john Irvin N. Romay my age is 16 years old
ill banned all the troublemaker in 6 hours if my close freind i will mute the player in 20 minutes
yes my freinds is Harlypasiosane,Getrex,amil,Kauro and Ainz
im online everyday except school hours
i hope to accept my application.
THANK YOU..>>>>> Poopeater

**Comment by Kaoruuu** [comment]
Unfortunately, we are not accepting applications anymore due to the quantity of the staffs in the team. Sorry for inconvenience but it was GM's decision.
Sincerely,

**Comment by Chris450** [comment]
😶

**Comment by Poopeater** [comment]
okee kaoruuu :D
